// Mocks generated by Mockito 5.0.17 from annotations
// in tdd/home/service/home_service.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:tdd/home/model/home_model.dart' as _i5;
import 'package:tdd/home/service/home_service.dart' as _i3;
import 'package:vexana/vexana.dart' as _i2;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeINetworkManager_0 extends _i1.Fake implements _i2.INetworkManager {}

/// A class which mocks [IHomeService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIHomeService extends _i1.Mock implements _i3.IHomeService {
  MockIHomeService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.INetworkManager get networkManager =>
      (super.noSuchMethod(Invocation.getter(#networkManager),
          returnValue: _FakeINetworkManager_0()) as _i2.INetworkManager);
  @override
  _i4.Future<List<_i5.ReqProfile>?> getAllItems() =>
      (super.noSuchMethod(Invocation.method(#getAllItems, []),
              returnValue: Future<List<_i5.ReqProfile>?>.value())
          as _i4.Future<List<_i5.ReqProfile>?>);
}
